### ISSUE TITLE
Add docs with suggestions on how to easily daemonize this for RL usage

### ISSUE THREAD

**Issue by dpritchett** [dpritchett/glisten#3]

**Comment by dpritchett** [comment]
cc @dan9186 - got any ideas here?

**Comment by dan9186** [comment]
I would at least do a dockerfile and systemd unit file for it.  You could also do an init.d script for it so that there's options.

For me it'd just depend on what system I was going to run it on, but I think those two would cover most of the situations I'd aim for.

**Comment by dpritchett** [comment]
Good call @dan9186.  I just added a basic `Dockerfile` and [put this on the Docker Hub](https://registry.hub.docker.com/u/dpritchett/glisten/build_id/71207/code/bgaen6qddxmtntr4byygjq/).  I'll read up on how systemd works and test out a basis dockerized systemd script  on a droplet next.

**Comment by dpritchett** [comment]
CoreOS + systemd setup verified.  Shutting this down for now.
